package com.dcai.semanticservice.ingestion

import org.apache.jena.rdf.model.ResourceFactory

internal object Dcterms {
    const val NAMESPACE = "http://purl.org/dc/terms/"
    val title = ResourceFactory.createProperty("${NAMESPACE}title")
}

internal object Prov {
    const val NAMESPACE = "http://www.w3.org/ns/prov#"
    val generated = ResourceFactory.createProperty("${NAMESPACE}generated")
    val generatedAtTime = ResourceFactory.createProperty("${NAMESPACE}generatedAtTime")
    val used = ResourceFactory.createProperty("${NAMESPACE}used")
    val wasDerivedFrom = ResourceFactory.createProperty("${NAMESPACE}wasDerivedFrom")
    val wasGeneratedBy = ResourceFactory.createProperty("${NAMESPACE}wasGeneratedBy")
}

internal object Dcai {
    const val NAMESPACE = "urn:dcai:ontology:"

    val SourceSystem = resource("SourceSystem")
    val SourceExtract = resource("SourceExtract")
    val SourceRecord = resource("SourceRecord")
    val ImportActivity = resource("ImportActivity")
    val PromotionActivity = resource("PromotionActivity")
    val ReasoningActivity = resource("ReasoningActivity")
    val OntologyActionType = resource("OntologyActionType")
    val OntologyActionRequest = resource("OntologyActionRequest")
    val OntologyActionExecution = resource("OntologyActionExecution")
    val ActionValidationReport = resource("ActionValidationReport")

    val Facility = resource("Facility")
    val DataHall = resource("DataHall")
    val InfrastructureZone = resource("InfrastructureZone")
    val InfrastructureRow = resource("InfrastructureRow")
    val Rack = resource("Rack")
    val InfrastructureAsset = resource("InfrastructureAsset")
    val PowerAsset = resource("PowerAsset")
    val UpsAsset = resource("UpsAsset")
    val PowerDistributionUnit = resource("PowerDistributionUnit")
    val GeneratorAsset = resource("GeneratorAsset")
    val CoolingAsset = resource("CoolingAsset")
    val CoolingLoop = resource("CoolingLoop")
    val ChilledWaterLoop = resource("ChilledWaterLoop")
    val CracAsset = resource("CracAsset")
    val ChillerAsset = resource("ChillerAsset")
    val ControlTelemetryAsset = resource("ControlTelemetryAsset")
    val TelemetryBridge = resource("TelemetryBridge")
    val ComputeCapacityGroup = resource("ComputeCapacityGroup")
    val GpuPod = resource("GpuPod")

    val InfrastructureIncident = resource("InfrastructureIncident")
    val WorkflowStage = resource("WorkflowStage")
    val WorkflowEvent = resource("WorkflowEvent")

    val DependencyEdge = resource("DependencyEdge")
    val DependencyPath = resource("DependencyPath")
    val PowerPath = resource("PowerPath")
    val CoolingPath = resource("CoolingPath")
    val TelemetryPath = resource("TelemetryPath")
    val RedundancyPath = resource("RedundancyPath")

    val ImpactObservation = resource("ImpactObservation")
    val TelemetryEvidence = resource("TelemetryEvidence")
    val ValidationEvidence = resource("ValidationEvidence")
    val WorkOrderEvidence = resource("WorkOrderEvidence")
    val DependencyImpactFinding = resource("DependencyImpactFinding")
    val BlastRadiusFinding = resource("BlastRadiusFinding")
    val RecoveryBlocker = resource("RecoveryBlocker")
    val RestoreReadinessFinding = resource("RestoreReadinessFinding")
    val TrustFinding = resource("TrustFinding")

    val CriticalityLevel = resource("CriticalityLevel")
    val OperationalStatus = resource("OperationalStatus")
    val IncidentStageState = resource("IncidentStageState")
    val WorkflowEventStatus = resource("WorkflowEventStatus")
    val DependencyRole = resource("DependencyRole")
    val ImpactScope = resource("ImpactScope")
    val RedundancyState = resource("RedundancyState")
    val MitigationState = resource("MitigationState")
    val VendorState = resource("VendorState")
    val EvidenceConfidenceState = resource("EvidenceConfidenceState")
    val TelemetryStatus = resource("TelemetryStatus")
    val ValidationStatus = resource("ValidationStatus")
    val WorkOrderStatus = resource("WorkOrderStatus")

    val hasIdentifier = property("hasIdentifier")
    val hasSourceSystem = property("hasSourceSystem")
    val hasSourceRecordId = property("hasSourceRecordId")
    val hasSourcePayloadHash = property("hasSourcePayloadHash")

    val zoneInFacility = property("zoneInFacility")
    val hallInFacility = property("hallInFacility")
    val zoneInHall = property("zoneInHall")
    val rowInZone = property("rowInZone")
    val rackInRow = property("rackInRow")
    val assetInRack = property("assetInRack")
    val assetInCapacityGroup = property("assetInCapacityGroup")
    val locatedIn = property("locatedIn")
    val hasAssetType = property("hasAssetType")
    val hasCriticalityLevel = property("hasCriticalityLevel")
    val hasOperationalStatus = property("hasOperationalStatus")
    val hasCriticality = property("hasCriticality")
    val hasOperationalState = property("hasOperationalState")

    val affectsAsset = property("affectsAsset")
    val hasCurrentStage = property("hasCurrentStage")
    val hasIncidentStageState = property("hasIncidentStageState")
    val enteredStage = property("enteredStage")
    val eventForIncident = property("eventForIncident")
    val hasEventId = property("hasEventId")
    val hasEventStatus = property("hasEventStatus")
    val hasWorkflowEventStatus = property("hasWorkflowEventStatus")
    val enteredAt = property("enteredAt")
    val exitedAt = property("exitedAt")
    val hasDurationHours = property("hasDurationHours")
    val hasDelayHours = property("hasDelayHours")

    val hasDependentAsset = property("hasDependentAsset")
    val hasDependencyAsset = property("hasDependencyAsset")
    val hasDependencyRole = property("hasDependencyRole")
    val hasDependencyRoleConcept = property("hasDependencyRoleConcept")
    val hasImpactScope = property("hasImpactScope")
    val hasImpactScopeConcept = property("hasImpactScopeConcept")
    val hasPathStep = property("hasPathStep")

    val impactForIncident = property("impactForIncident")
    val estimatedCapacityRiskKw = property("estimatedCapacityRiskKw")
    val affectedGpuCount = property("affectedGpuCount")
    val affectedRackCount = property("affectedRackCount")
    val hasRedundancyState = property("hasRedundancyState")
    val hasRedundancyStateConcept = property("hasRedundancyStateConcept")
    val hasMitigationState = property("hasMitigationState")
    val hasMitigationStateConcept = property("hasMitigationStateConcept")
    val hasVendorState = property("hasVendorState")
    val hasVendorStateConcept = property("hasVendorStateConcept")
    val vendorEtaAt = property("vendorEtaAt")

    val supportsFact = property("supportsFact")
    val hasConfidenceState = property("hasConfidenceState")
    val hasEvidenceConfidence = property("hasEvidenceConfidence")
    val hasEvidenceTimestamp = property("hasEvidenceTimestamp")
    val hasMetricName = property("hasMetricName")
    val hasMetricValue = property("hasMetricValue")
    val hasMetricUnit = property("hasMetricUnit")
    val hasTelemetryStatus = property("hasTelemetryStatus")
    val hasTelemetryState = property("hasTelemetryState")
    val hasValidationId = property("hasValidationId")
    val hasValidationStatus = property("hasValidationStatus")
    val hasValidationState = property("hasValidationState")
    val hasWorkOrderId = property("hasWorkOrderId")
    val hasWorkOrderStatus = property("hasWorkOrderStatus")
    val hasWorkOrderState = property("hasWorkOrderState")
    val hasAssignedTeam = property("hasAssignedTeam")
    val hasFindingSummary = property("hasFindingSummary")
    val hasEvidenceSeverity = property("hasEvidenceSeverity")
    val createdAt = property("createdAt")
    val hasActionType = property("hasActionType")
    val hasActionStatus = property("hasActionStatus")
    val hasActionReason = property("hasActionReason")
    val hasActorId = property("hasActorId")
    val hasAssigneeId = property("hasAssigneeId")
    val hasIdempotencyKey = property("hasIdempotencyKey")
    val hasTargetObject = property("hasTargetObject")
    val hasActionValidationStatus = property("hasActionValidationStatus")
    val hasReviewedStatus = property("hasReviewedStatus")
    val hasReviewSummary = property("hasReviewSummary")
    val hasSupportingEvidence = property("hasSupportingEvidence")

    private fun resource(localName: String) = ResourceFactory.createResource("$NAMESPACE$localName")

    private fun property(localName: String) = ResourceFactory.createProperty("$NAMESPACE$localName")
}
