package com.dcai.semanticservice.dynamic

import com.dcai.semanticservice.ingestion.AssetClass
import com.dcai.semanticservice.ingestion.AssetSourceRecord
import com.dcai.semanticservice.ingestion.DependencyPathClass
import com.dcai.semanticservice.ingestion.DependencySourceRecord
import com.dcai.semanticservice.ingestion.EvidenceClass
import com.dcai.semanticservice.ingestion.EvidenceSourceRecord
import com.dcai.semanticservice.ingestion.FacilitySourceRecord
import com.dcai.semanticservice.ingestion.ImpactSourceRecord
import com.dcai.semanticservice.ingestion.IncidentSourceRecord
import com.dcai.semanticservice.ingestion.SourceExtractBatch
import com.dcai.semanticservice.ingestion.WorkflowEventSourceRecord
import com.dcai.semanticservice.ingestion.ZoneSourceRecord
import java.math.BigDecimal
import java.time.Instant

object LocalDynamicPlaybackScenario {
    const val DEFAULT_SCENARIO_ID = "local-dynamic-playback-v1"
    const val DEFAULT_PLAYBACK_BATCH_ID = "local-dynamic-playback-batch-v1"
    const val DEFAULT_ACTION_AUDIT_RELEASE_ID = "local-dynamic-action-audit-v1"

    fun scenario(
        scenarioId: String = DEFAULT_SCENARIO_ID,
        playbackBatchId: String = DEFAULT_PLAYBACK_BATCH_ID,
    ): DynamicPlaybackScenario {
        val base = Instant.parse("2026-06-10T00:00:00Z")
        return DynamicPlaybackScenario(
            scenarioId = scenarioId,
            playbackBatchId = playbackBatchId,
            generatedAt = base,
            steps = listOf(
                step(
                    step = 1,
                    importedAt = base.plusSeconds(300),
                    releaseId = "$scenarioId-step-01",
                    reasoningRunId = "$scenarioId-reasoning-01",
                    stage = "DETECTION",
                    stageLabel = "Detection",
                    workflowStatus = "OPEN",
                    telemetryStatus = "ALERTING",
                    confidence = "TRUSTED",
                    validationStatus = null,
                    workOrderStatus = "REQUESTED",
                    mitigationState = "NOT_STARTED",
                    vendorState = "ETA_PENDING",
                    capacityRiskKw = "420.0",
                    gpuCount = 96,
                    beforeState = "SOURCE_EXPORT_RECEIVED",
                    afterState = "CANONICAL_PROMOTED",
                    beforeReasoningState = "NO_REASONING_OUTPUT",
                    afterReasoningState = "DEPENDENCY_EXPOSURE_INFERRED",
                    beforeTrustState = "UNKNOWN",
                    afterTrustState = "TRUSTED_TELEMETRY",
                    beforeBlastRadiusCount = 0,
                    afterBlastRadiusCount = 1,
                    actionLifecycleState = "NONE",
                    eventKind = "TELEMETRY_IMPACT_CHANGE",
                    sourceFamily = "telemetry-impact",
                    sourceRecordId = "SRC-DYN-IMPACT-001",
                    summary = "Telemetry export shows UPS degradation and initial GPU capacity risk.",
                ),
                step(
                    step = 2,
                    importedAt = base.plusSeconds(900),
                    releaseId = "$scenarioId-step-02",
                    reasoningRunId = "$scenarioId-reasoning-02",
                    stage = "VALIDATION",
                    stageLabel = "Validation",
                    workflowStatus = "OPEN",
                    telemetryStatus = "GAP",
                    confidence = "CONFLICTED",
                    validationStatus = "CONFLICTING",
                    workOrderStatus = "ASSIGNED",
                    mitigationState = "RUNNING_DEGRADED",
                    vendorState = "ETA_PENDING",
                    capacityRiskKw = "520.0",
                    gpuCount = 128,
                    beforeState = "CANONICAL_PROMOTED",
                    afterState = "CANONICAL_PROMOTED_WITH_CONFLICT",
                    beforeReasoningState = "DEPENDENCY_EXPOSURE_INFERRED",
                    afterReasoningState = "TRUST_REVIEW_REQUIRED",
                    beforeTrustState = "TRUSTED_TELEMETRY",
                    afterTrustState = "CONFLICTING_VALIDATION",
                    beforeBlastRadiusCount = 1,
                    afterBlastRadiusCount = 2,
                    actionLifecycleState = "QUEUED",
                    eventKind = "VALIDATION_CONFLICT",
                    sourceFamily = "work-order-validation",
                    sourceRecordId = "SRC-DYN-VALIDATION-002",
                    summary = "Validation evidence conflicts with telemetry while the work order is assigned.",
                ),
                step(
                    step = 3,
                    importedAt = base.plusSeconds(1800),
                    releaseId = "$scenarioId-step-03",
                    reasoningRunId = "$scenarioId-reasoning-03",
                    stage = "VENDOR_WAIT",
                    stageLabel = "Vendor wait",
                    workflowStatus = "BLOCKED",
                    telemetryStatus = "ALERTING",
                    confidence = "LOW_CONFIDENCE",
                    validationStatus = "FAILED",
                    workOrderStatus = "WAITING_VENDOR",
                    mitigationState = "RUNNING_DEGRADED",
                    vendorState = "ETA_MISSED",
                    capacityRiskKw = "680.0",
                    gpuCount = 192,
                    beforeState = "CANONICAL_PROMOTED_WITH_CONFLICT",
                    afterState = "CANONICAL_PROMOTED_WITH_BLOCKER",
                    beforeReasoningState = "TRUST_REVIEW_REQUIRED",
                    afterReasoningState = "RESTORE_BLOCKED",
                    beforeTrustState = "CONFLICTING_VALIDATION",
                    afterTrustState = "LOW_CONFIDENCE_IMPACT",
                    beforeBlastRadiusCount = 2,
                    afterBlastRadiusCount = 4,
                    actionLifecycleState = "IN_REVIEW",
                    eventKind = "VENDOR_RECOVERY_BLOCKER",
                    sourceFamily = "incident-workflow",
                    sourceRecordId = "SRC-DYN-WF-003",
                    summary = "Vendor ETA miss creates a restore blocker and expands blast-radius exposure.",
                ),
                step(
                    step = 4,
                    importedAt = base.plusSeconds(3600),
                    releaseId = "$scenarioId-step-04",
                    reasoningRunId = "$scenarioId-reasoning-04",
                    stage = "RESTORE_READY",
                    stageLabel = "Restore ready",
                    workflowStatus = "READY",
                    telemetryStatus = "RECOVERING",
                    confidence = "TRUSTED",
                    validationStatus = "PASSED",
                    workOrderStatus = "COMPLETED",
                    mitigationState = "MITIGATED",
                    vendorState = "ETA_MET",
                    capacityRiskKw = "120.0",
                    gpuCount = 24,
                    beforeState = "CANONICAL_PROMOTED_WITH_BLOCKER",
                    afterState = "CANONICAL_PROMOTED_RESTORING",
                    beforeReasoningState = "RESTORE_BLOCKED",
                    afterReasoningState = "RESTORE_READY_WITH_MONITORING",
                    beforeTrustState = "LOW_CONFIDENCE_IMPACT",
                    afterTrustState = "TRUSTED_VALIDATION",
                    beforeBlastRadiusCount = 4,
                    afterBlastRadiusCount = 1,
                    actionLifecycleState = "APPROVED",
                    eventKind = "RESTORE_READINESS_CHANGE",
                    sourceFamily = "work-order-validation",
                    sourceRecordId = "SRC-DYN-VALIDATION-002",
                    summary = "Validation and completed work order reduce risk and move the action toward approval.",
                ),
            ),
        )
    }

    private fun step(
        step: Int,
        importedAt: Instant,
        releaseId: String,
        reasoningRunId: String,
        stage: String,
        stageLabel: String,
        workflowStatus: String,
        telemetryStatus: String,
        confidence: String,
        validationStatus: String?,
        workOrderStatus: String,
        mitigationState: String,
        vendorState: String,
        capacityRiskKw: String,
        gpuCount: Int,
        beforeState: String,
        afterState: String,
        beforeReasoningState: String,
        afterReasoningState: String,
        beforeTrustState: String,
        afterTrustState: String,
        beforeBlastRadiusCount: Int,
        afterBlastRadiusCount: Int,
        actionLifecycleState: String,
        eventKind: String,
        sourceFamily: String,
        sourceRecordId: String,
        summary: String,
    ): DynamicPlaybackStep {
        return DynamicPlaybackStep(
            step = step,
            sourceReleaseId = releaseId,
            reasoningRunId = reasoningRunId,
            sourceBatch = batch(
                releaseId = releaseId,
                importedAt = importedAt,
                stage = stage,
                stageLabel = stageLabel,
                workflowStatus = workflowStatus,
                telemetryStatus = telemetryStatus,
                confidence = confidence,
                validationStatus = validationStatus,
                workOrderStatus = workOrderStatus,
                mitigationState = mitigationState,
                vendorState = vendorState,
                capacityRiskKw = capacityRiskKw,
                gpuCount = gpuCount,
            ),
            event = DynamicPlaybackEventRecord(
                eventId = "DYN-EVENT-$step",
                occurredAt = importedAt,
                incidentId = INCIDENT_ID,
                eventKind = eventKind,
                sourceFamily = sourceFamily,
                sourceRecordUri = "urn:dcai:source-record:$SOURCE_SYSTEM_ID:$sourceRecordId",
                beforeState = beforeState,
                afterState = afterState,
                beforeReasoningState = beforeReasoningState,
                afterReasoningState = afterReasoningState,
                beforeTrustState = beforeTrustState,
                afterTrustState = afterTrustState,
                beforeBlastRadiusCount = beforeBlastRadiusCount,
                afterBlastRadiusCount = afterBlastRadiusCount,
                actionLifecycleState = actionLifecycleState,
                summary = summary,
            ),
        )
    }

    private fun batch(
        releaseId: String,
        importedAt: Instant,
        stage: String,
        stageLabel: String,
        workflowStatus: String,
        telemetryStatus: String,
        confidence: String,
        validationStatus: String?,
        workOrderStatus: String,
        mitigationState: String,
        vendorState: String,
        capacityRiskKw: String,
        gpuCount: Int,
    ): SourceExtractBatch {
        return SourceExtractBatch(
            batchId = releaseId,
            sourceSystemId = SOURCE_SYSTEM_ID,
            sourceSystemLabel = "Local dynamic source-system playback",
            importedAt = importedAt,
            facilities = listOf(FacilitySourceRecord("SRC-DYN-FAC-001", "sha256:$releaseId:facility", FACILITY_ID, "AI GPU Hall Dynamic")),
            zones = listOf(ZoneSourceRecord("SRC-DYN-ZONE-001", "sha256:$releaseId:zone", ZONE_ID, FACILITY_ID, "Zone Dynamic A")),
            assets = listOf(
                AssetSourceRecord(
                    recordId = "SRC-DYN-ASSET-GPU-001",
                    payloadHash = "sha256:$releaseId:asset-gpu",
                    assetId = GPU_ASSET_ID,
                    zoneId = ZONE_ID,
                    assetType = "GPU_RACK_ROW",
                    criticalityLevel = "CRITICAL",
                    operationalStatus = if (mitigationState == "MITIGATED") "RECOVERING" else "DEGRADED",
                    hallId = "HALL-DYN-A",
                    rowId = "ROW-DYN-A",
                    rackId = "RACK-DYN-A01",
                    capacityGroupId = "GPU-POD-DYN-A",
                ),
                AssetSourceRecord(
                    recordId = "SRC-DYN-ASSET-UPS-001",
                    payloadHash = "sha256:$releaseId:asset-ups",
                    assetId = UPS_ASSET_ID,
                    zoneId = ZONE_ID,
                    assetType = "UPS_MODULE",
                    criticalityLevel = "CRITICAL",
                    operationalStatus = if (mitigationState == "MITIGATED") "RECOVERING" else "DEGRADED",
                    assetClass = AssetClass.POWER,
                ),
                AssetSourceRecord(
                    recordId = "SRC-DYN-ASSET-TEL-001",
                    payloadHash = "sha256:$releaseId:asset-telemetry",
                    assetId = TELEMETRY_ASSET_ID,
                    zoneId = ZONE_ID,
                    assetType = "TELEMETRY_BRIDGE",
                    criticalityLevel = "HIGH",
                    operationalStatus = telemetryStatus,
                    assetClass = AssetClass.CONTROL_TELEMETRY,
                ),
                AssetSourceRecord(
                    recordId = "SRC-DYN-ASSET-COOL-001",
                    payloadHash = "sha256:$releaseId:asset-cooling",
                    assetId = COOLING_ASSET_ID,
                    zoneId = ZONE_ID,
                    assetType = "COOLING_LOOP",
                    criticalityLevel = "HIGH",
                    operationalStatus = if (mitigationState == "MITIGATED") "RUNNING" else "AT_RISK",
                    assetClass = AssetClass.COOLING,
                ),
            ),
            incidents = listOf(
                IncidentSourceRecord(
                    recordId = "SRC-DYN-INC-001",
                    payloadHash = "sha256:$releaseId:incident",
                    incidentId = INCIDENT_ID,
                    assetId = GPU_ASSET_ID,
                    currentStageId = stage,
                    currentStageLabel = stageLabel,
                ),
            ),
            dependencies = listOf(
                DependencySourceRecord(
                    recordId = "SRC-DYN-DEP-POWER",
                    payloadHash = "sha256:$releaseId:dep-power",
                    edgeId = "EDGE-DYN-UPS-GPU",
                    dependentAssetId = GPU_ASSET_ID,
                    dependencyAssetId = UPS_ASSET_ID,
                    dependencyRole = "POWER_SUPPLY",
                    impactScope = "RACK_ROW",
                    pathId = "PATH-DYN-POWER",
                    pathClass = DependencyPathClass.POWER,
                ),
                DependencySourceRecord(
                    recordId = "SRC-DYN-DEP-TELEMETRY",
                    payloadHash = "sha256:$releaseId:dep-telemetry",
                    edgeId = "EDGE-DYN-TEL-GPU",
                    dependentAssetId = GPU_ASSET_ID,
                    dependencyAssetId = TELEMETRY_ASSET_ID,
                    dependencyRole = "TELEMETRY_SOURCE",
                    impactScope = "GPU_POD",
                    pathId = "PATH-DYN-TELEMETRY",
                    pathClass = DependencyPathClass.TELEMETRY,
                ),
                DependencySourceRecord(
                    recordId = "SRC-DYN-DEP-COOLING",
                    payloadHash = "sha256:$releaseId:dep-cooling",
                    edgeId = "EDGE-DYN-COOL-GPU",
                    dependentAssetId = GPU_ASSET_ID,
                    dependencyAssetId = COOLING_ASSET_ID,
                    dependencyRole = "COOLING_SUPPLY",
                    impactScope = "GPU_POD",
                    pathId = "PATH-DYN-COOLING",
                    pathClass = DependencyPathClass.COOLING,
                ),
            ),
            workflowEvents = listOf(
                WorkflowEventSourceRecord(
                    recordId = "SRC-DYN-WF-003",
                    payloadHash = "sha256:$releaseId:workflow",
                    eventId = "EVT-DYN-$stage",
                    incidentId = INCIDENT_ID,
                    enteredStageId = stage,
                    enteredStageLabel = stageLabel,
                    status = workflowStatus,
                    enteredAt = importedAt.minusSeconds(600),
                    durationHours = BigDecimal("1.5"),
                    delayHours = if (workflowStatus == "BLOCKED") BigDecimal("1.0") else BigDecimal("0.0"),
                ),
            ),
            evidence = listOfNotNull(
                EvidenceSourceRecord(
                    recordId = "SRC-DYN-TELEMETRY-001",
                    payloadHash = "sha256:$releaseId:telemetry",
                    evidenceId = "EVID-DYN-TELEMETRY",
                    evidenceClass = EvidenceClass.TELEMETRY,
                    supportsId = IMPACT_ID,
                    confidenceState = confidence,
                    timestamp = importedAt.minusSeconds(300),
                    metricName = "gpu_capacity_risk_kw",
                    metricValue = BigDecimal(capacityRiskKw),
                    metricUnit = "kW",
                    telemetryStatus = telemetryStatus,
                ),
                validationStatus?.let {
                    EvidenceSourceRecord(
                        recordId = "SRC-DYN-VALIDATION-002",
                        payloadHash = "sha256:$releaseId:validation",
                        evidenceId = "EVID-DYN-VALIDATION",
                        evidenceClass = EvidenceClass.VALIDATION,
                        supportsId = INCIDENT_ID,
                        confidenceState = confidence,
                        timestamp = importedAt.minusSeconds(120),
                        validationId = "VAL-DYN-001",
                        validationStatus = it,
                    )
                },
                EvidenceSourceRecord(
                    recordId = "SRC-DYN-WORKORDER-001",
                    payloadHash = "sha256:$releaseId:work-order",
                    evidenceId = "EVID-DYN-WORKORDER",
                    evidenceClass = EvidenceClass.WORK_ORDER,
                    supportsId = INCIDENT_ID,
                    confidenceState = confidence,
                    timestamp = importedAt.minusSeconds(60),
                    workOrderId = "WO-DYN-001",
                    workOrderStatus = workOrderStatus,
                    assignedTeam = "power-ops",
                ),
            ),
            impacts = listOf(
                ImpactSourceRecord(
                    recordId = "SRC-DYN-IMPACT-001",
                    payloadHash = "sha256:$releaseId:impact",
                    impactId = IMPACT_ID,
                    incidentId = INCIDENT_ID,
                    estimatedCapacityRiskKw = BigDecimal(capacityRiskKw),
                    affectedGpuCount = gpuCount,
                    affectedRackCount = if (gpuCount > 100) 4 else 1,
                    redundancyState = if (capacityRiskKw.toBigDecimal() > BigDecimal("300")) "N-1" else "NOMINAL",
                    mitigationState = mitigationState,
                    vendorState = vendorState,
                    vendorEtaAt = importedAt.plusSeconds(1800),
                ),
            ),
        )
    }

    private const val SOURCE_SYSTEM_ID = "local-dynamic-source-systems"
    private const val FACILITY_ID = "FAC-DYN-GPU"
    private const val ZONE_ID = "ZONE-DYN-A"
    private const val INCIDENT_ID = "INC-DYN-001"
    private const val IMPACT_ID = "IMPACT-DYN-001"
    private const val GPU_ASSET_ID = "ASSET-DYN-GPU-ROW-A"
    private const val UPS_ASSET_ID = "ASSET-DYN-UPS-A"
    private const val TELEMETRY_ASSET_ID = "ASSET-DYN-TELEMETRY-A"
    private const val COOLING_ASSET_ID = "ASSET-DYN-COOLING-A"
}
